//! Deterministic synthetic corpus generation shared by the criterion benches and the
//! memory profiler binary.
//!
//! The corpus mimics the real RFC corpus shape: a fixed vocabulary sampled with a
//! harmonic (Zipf-ish) distribution so a few terms appear in nearly every document and
//! most terms are rare. Generation is seeded, so every run produces identical data.

use std::collections::HashMap;

use rand::distributions::{Distribution, WeightedIndex};
use rand::rngs::SmallRng;
use rand::SeedableRng;
use rfsee_tf_idf::{RfcEntry, TfIdf};

/// Default number of synthetic documents; override with the RFSEE_BENCH_DOCS env var.
pub const DEFAULT_DOCS: usize = 1_000;
/// Tokens generated per document, roughly matching a real RFC's word count.
pub const TOKENS_PER_DOC: usize = 2_500;
/// Size of the vocabulary documents are sampled from.
pub const VOCAB_SIZE: usize = 20_000;
/// Fixed seed for reproducible corpora across runs and machines.
const SEED: u64 = 0x5EED;

/// Number of documents to use, from `RFSEE_BENCH_DOCS` or [`DEFAULT_DOCS`].
pub fn doc_count_from_env() -> usize {
    std::env::var("RFSEE_BENCH_DOCS")
        .ok()
        .and_then(|v| v.parse().ok())
        .unwrap_or(DEFAULT_DOCS)
}

fn vocabulary() -> Vec<String> {
    (0..VOCAB_SIZE).map(|i| format!("term{i}")).collect()
}

/// Weights 1, 1/2, 1/3, ... so term0 is "the"-like common and high indices are rare.
fn harmonic_weights() -> WeightedIndex<f64> {
    WeightedIndex::new((1..=VOCAB_SIZE).map(|i| 1.0 / i as f64)).unwrap()
}

fn make_entry(
    vocab: &[String],
    dist: &WeightedIndex<f64>,
    rng: &mut SmallRng,
    number: i32,
) -> RfcEntry {
    let mut content = String::with_capacity(TOKENS_PER_DOC * 8);
    for _ in 0..TOKENS_PER_DOC {
        content.push_str(&vocab[dist.sample(rng)]);
        content.push(' ');
    }
    RfcEntry {
        number,
        url: format!("https://rfsee.com/{number}"),
        title: format!("RFC {number}"),
        content: Some(content),
    }
}

/// The whole corpus materialized at once, mirroring what `par_load_rfcs` does today:
/// every document's content is held in memory before processing starts.
pub fn corpus(n_docs: usize) -> Vec<RfcEntry> {
    corpus_stream(n_docs).collect()
}

/// A streaming view of the corpus that generates one document at a time, mirroring
/// the shape of the pipeline after fetched documents are processed as they arrive.
pub fn corpus_stream(n_docs: usize) -> CorpusStream {
    CorpusStream {
        vocab: vocabulary(),
        dist: harmonic_weights(),
        rng: SmallRng::seed_from_u64(SEED),
        next: 1,
        total: n_docs as i32,
    }
}

pub struct CorpusStream {
    vocab: Vec<String>,
    dist: WeightedIndex<f64>,
    rng: SmallRng,
    next: i32,
    total: i32,
}

impl Iterator for CorpusStream {
    type Item = RfcEntry;

    fn next(&mut self) -> Option<Self::Item> {
        if self.next > self.total {
            return None;
        }
        let entry = make_entry(&self.vocab, &self.dist, &mut self.rng, self.next);
        self.next += 1;
        Some(entry)
    }
}

extern "C" fn noop_cb(_: *const std::ffi::c_char) {}

/// Process entries into a finished index (term frequencies + IDF + term scores).
pub fn build_index(entries: impl IntoIterator<Item = RfcEntry>) -> TfIdf {
    let mut index = TfIdf::default();
    for entry in entries {
        index.add_rfc_entry(entry);
    }
    index.finish(noop_cb);
    index
}

/// Documents per term map for the `combine_scores` benches. Common terms in the real
/// index appear in nearly all docs.
pub const SCORE_MAP_DOCS_PER_TERM: usize = 10_000;
/// Number of query terms whose score maps are combined.
pub const SCORE_MAP_QUERY_TERMS: usize = 5;

/// Synthetic per-term score maps. Doc ids are shifted per term so maps partially
/// overlap, and scores vary via a cheap hash.
pub fn score_maps(docs_per_term: usize, query_terms: usize) -> Vec<HashMap<i32, i32>> {
    (0..query_terms)
        .map(|term| {
            (0..docs_per_term as i32)
                .map(|doc| (doc + term as i32, (doc * 31 + term as i32) % 1_000_000))
                .collect()
        })
        .collect()
}

/// Sizes generated by default when `just generate-bench-data` is run without
/// arguments.
pub const DEFAULT_BENCH_SIZES: &[usize] = &[100, 1_000, 10_000];
/// Dataset size benches use when RFSEE_BENCH_SIZE is unset.
pub const DEFAULT_BENCH_SIZE: usize = 1_000;

/// Root of the generated benchmark data (gitignored). Populated by
/// `just generate-bench-data`; holds one subdirectory per dataset size.
pub fn bench_data_dir() -> std::path::PathBuf {
    concat!(env!("CARGO_MANIFEST_DIR"), "/../bench-data").into()
}

/// Dataset size selected for this bench run: RFSEE_BENCH_SIZE or
/// [`DEFAULT_BENCH_SIZE`].
pub fn bench_size_from_env() -> usize {
    std::env::var("RFSEE_BENCH_SIZE")
        .ok()
        .and_then(|v| v.parse().ok())
        .unwrap_or(DEFAULT_BENCH_SIZE)
}

/// Directory of the currently selected dataset size.
pub fn bench_size_dir() -> std::path::PathBuf {
    bench_data_dir().join(bench_size_from_env().to_string())
}

fn open_sized(name: &str) -> std::fs::File {
    let path = bench_size_dir().join(name);
    std::fs::File::open(&path).unwrap_or_else(|e| {
        let mut available: Vec<_> = std::fs::read_dir(bench_data_dir())
            .map(|rd| {
                rd.filter_map(|e| e.ok())
                    .filter(|e| e.path().is_dir())
                    .filter_map(|e| e.file_name().into_string().ok())
                    .collect()
            })
            .unwrap_or_default();
        available.sort();
        panic!(
            "cannot open {}: {e}\nrun `just generate-bench-data` first (available sizes: {})",
            path.display(),
            if available.is_empty() {
                "none".to_string()
            } else {
                available.join(", ")
            }
        )
    })
}

/// The synthetic corpus for the selected size (one JSON entry per line), used by
/// the index-pipeline bench.
pub fn load_corpus() -> Vec<rfsee_tf_idf::RfcEntry> {
    let mut bytes = std::fs::read(bench_size_dir().join("corpus.jsonl")).unwrap_or_else(|e| {
        panic!("cannot read corpus.jsonl: {e}\nrun `just generate-bench-data` first")
    });
    bytes
        .split_mut(|&b| b == b'\n')
        .filter(|line| !line.is_empty())
        .map(|line| simd_json::from_slice(line).expect("corrupt corpus.jsonl"))
        .collect()
}

/// The finished index for the selected size, used by the search and serde benches.
pub fn load_index() -> rfsee_tf_idf::Index {
    simd_json::from_reader(open_sized("index.json")).expect("corrupt index.json")
}

/// Path to the on-disk index file for the selected size, for the cold-search
/// benches (read + parse + search).
pub fn bench_index_path() -> std::path::PathBuf {
    let path = bench_size_dir().join("index.json");
    if !path.exists() {
        panic!(
            "{} missing - run `just generate-bench-data` first",
            path.display()
        );
    }
    path
}

/// The score maps shared by all sizes (the `combine_scores` input is
/// size-independent), used by the `combine_scores` benches.
pub fn load_score_maps() -> Vec<HashMap<i32, i32>> {
    let path = bench_data_dir().join("score-maps.json");
    let file = std::fs::File::open(&path).unwrap_or_else(|e| {
        panic!(
            "cannot open {}: {e}\nrun `just generate-bench-data` first",
            path.display()
        )
    });
    simd_json::from_reader(file).expect("corrupt score-maps.json")
}
